services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - verdaccio_storage:/verdaccio/storage
      - verdaccio_config:/verdaccio/conf
    environment:
      - VERDACCIO_PORT=4873

volumes:
  verdaccio_storage:
  verdaccio_config:
